// BANCO DE DADOS (UBSF)
const baseDeDados = {
    "Acácio Figueiredo (Catingueira)": "UBSF Acácio Figueiredo",
    "Alto Branco": "UBSF Alto Branco",
    "Alto da Serra (Cuités)": "UBSF Cuités (Alto da Serra)",
    "Altos de Campina (Cidades)": "UBSF Bairro das Cidades",
    "Araxá": "UBSF Araxá",
    "Bairro das Cidades": "UBSF Bairro das Cidades",
    "Bairro das Nações": "UBSF Bairro das Nações",
    "Bela Vista": "UBSF Bela Vista",
    "Belo Monte (Nova Brasília)": "UBSF Nova Brasília (Belo Monte)",
    "Bodocongó": "UBSF Bodocongó",
    "Castelo Branco": "UBSF Castelo Branco",
    "Catolé": "UBSF Catolé",
    "Catolé de Zé Ferreira": "UBSF Catolé de Zé Ferreira",
    "Centenário": "UBSF Centenário",
    "Centro": "Centro de Saúde Francisco Pinto",
    "Colinas do Oeste": "UBSF Colinas do Oeste",
    "Colinas do Sol (Malvinas)": "UBSF Malvinas",
    "Complexo Aluizio Campos (Ligeiro)": "UBSF Aluizio Campos",
    "Conceição": "UBSF Conceição",
    "Conjunto Acácio Figueiredo (Três Irmãs)": "UBSF Três Irmãs",
    "Conjunto Chico Mendes (Malvinas)": "UBSF Chico Mendes",
    "Conjunto Cinza (Três Irmãs)": "UBSF Conjunto Cinza",
    "Conjunto Irmãos Alexandrino": "UBSF Irmãos Alexandrino",
    "Conjunto Mariz (Malvinas)": "UBSF Malvinas",
    "Conjunto Pedro Gondim (Cidades)": "UBSF Pedro Gondim",
    "Conjunto Raimundo Suassuna (Três Irmãs)": "UBSF Raimundo Suassuna",
    "Conjunto Ronaldo Cunha Lima (Três Irmãs)": "UBSF Ronaldo Cunha Lima",
    "Conjunto Severino Cabral (Bodocongó)": "UBSF Severino Cabral",
    "Cruzeiro": "UBSF Cruzeiro",
    "Cuités": "UBSF Cuités",
    "Dinamérica": "UBSF Dinamérica",
    "Distrito de Catolé": "UBSF Distrito de Catolé",
    "Distrito dos Mecânicos (Jardim Paulistano)": "UBSF Distrito dos Mecânicos",
    "Distrito Industrial": "UBSF Distrito Industrial",
    "Estação Velha": "UBSF Estação Velha",
    "Galante": "UBSF Galante",
    "Glória 1 (Nova Brasília)": "UBSF Nova Brasília (Glória)",
    "Glória 2 (Nova Brasília)": "UBSF Nova Brasília (Glória)",
    "Itararé": "UBSF Itararé",
    "Jardim América (Nova Brasília)": "UBSF Nova Brasília",
    "Jardim Bellagio (Três Irmãs)": "UBSF Três Irmãs",
    "Jardim Borborema": "UBSF Jardim Borborema",
    "Jardim Continental": "UBSF Jardim Continental",
    "Jardim Europa (Nova Brasília)": "UBSF Nova Brasília",
    "Jardim Menezes": "UBSF Jardim Menezes",
    "Jardim Paulistano": "UBSF Jardim Paulistano",
    "Jardim Quarenta": "UBSF Jardim Quarenta",
    "Jardim Tavares": "UBSF Jardim Tavares",
    "Jardim Verdejante": "UBSF Jardim Verdejante",
    "Jardim Vitória": "UBSF Jardim Vitória",
    "Jardim Walnyza (Velame)": "UBSF Velame",
    "Jeremias": "UBSF Jeremias",
    "José Pinheiro": "UBSF José Pinheiro",
    "Juracy Palhano (Nações)": "UBSF Nações",
    "Lauritzen": "UBSF Lauritzen",
    "Liberdade": "UBSF Liberdade",
    "Ligeiro": "UBSF Ligeiro",
    "Loteamento Alameda (Serrotão)": "UBSF Serrotão",
    "Loteamento Altiplano Serra Rica (Cuités)": "UBSF Cuités",
    "Loteamento Bento Figueiredo (Monte Santo/Univ.)": "UBSF Bento Figueiredo",
    "Loteamento Grande Campina (Serrotão)": "UBSF Serrotão",
    "Loteamento João Paulo II (Ramadinha)": "UBSF Ramadinha",
    "Loteamento Portal dos Bosques (Serrotão)": "UBSF Serrotão",
    "Louzeiro": "UBSF Louzeiro",
    "Malvinas": "UBSF Malvinas",
    "Marinho": "UBSF Marinho",
    "Mirante": "UBSF Mirante",
    "Monte Castelo": "UBSF Monte Castelo",
    "Monte Santo": "UBSF Monte Santo",
    "Mutirão do Serrotão": "UBSF Mutirão do Serrotão",
    "Nova Brasília": "UBSF Nova Brasília",
    "Novo Araxá": "UBSF Novo Araxá",
    "Novo Bodocongó": "UBSF Novo Bodocongó",
    "Novo Cruzeiro": "UBSF Novo Cruzeiro",
    "Novo Horizonte": "UBSF Novo Horizonte",
    "Palmeira": "UBSF Palmeira",
    "Palmeira Imperial": "UBSF Palmeira Imperial",
    "Pedregal": "UBSF Pedregal",
    "Ponto Cem Réis": "UBSF Ponto Cem Réis",
    "Portal de Campina (Três Irmãs)": "UBSF Três Irmãs",
    "Portal Sudoeste (Três Irmãs)": "UBSF Portal Sudoeste",
    "Prata": "Centro de Saúde da Prata",
    "Presidente Médici": "UBSF Presidente Médici",
    "Quarenta": "UBSF Quarenta",
    "Ramadinha (I e II)": "UBSF Ramadinha",
    "Ressurreição 1 (Acácio Figueiredo e Presidente Médici)": "UBSF Ressurreição",
    "Ressurreição 2": "UBSF Ressurreição 2",
    "Rocha Cavalcante (Três Irmãs)": "UBSF Rocha Cavalcante",
    "Rosa Cruz (Cruzeiro)": "UBSF Rosa Cruz",
    "Sandra Cavalcante": "UBSF Sandra Cavalcante",
    "Santa Cruz": "UBSF Santa Cruz",
    "Santa Rosa": "UBSF Santa Rosa",
    "Santa Terezinha": "UBSF Santa Terezinha",
    "Santo Antônio": "UBSF Santo Antônio",
    "São Januário (Bodocongó)": "UBSF Bodocongó",
    "São José": "UBSF São José",
    "São José da Mata": "UBSF São José da Mata",
    "Serra da Borborema": "UBSF Serra da Borborema",
    "Serrotão": "UBSF Serrotão",
    "Sítio Estreito (I, II e III)": "UBSF Sítio Estreito",
    "Sítio Lucas (I e II)": "UBSF Sítio Lucas",
    "Tambor": "UBSF Tambor",
    "Três Irmãs": "UBSF Três Irmãs",
    "Universitário": "UBSF Universitário",
    "Velame": "UBSF Velame",
    "Vila dos Teimosos (Bodocongó)": "UBSF Bodocongó",
    "Vila Olímpia (Cuités)": "UBSF Cuités"
};